import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from conftest import make_disk

from diskatlas.config import load_config
from diskatlas.db import Database, alembic_config
from diskatlas.services import ingest
from diskatlas.tools.dbcopy import copy_database


def test_load_config_file_and_env(tmp_path, monkeypatch):
    path = tmp_path / "c.toml"
    path.write_text('database_url = "sqlite:///x.db"\n[agent]\npoll_interval = 2.5\n'
                    '[server]\nport = 9000\n', encoding="utf-8")
    monkeypatch.setenv("DISKATLAS_PORT", "9100")
    monkeypatch.setenv("DISKATLAS_API_TOKEN", "t")
    cfg = load_config(path)
    assert cfg.database_url == "sqlite:///x.db"
    assert cfg.agent.poll_interval == 2.5
    assert cfg.server.port == 9100
    assert cfg.agent.api_token == "t"
    assert not hasattr(cfg.server, "api_token"), "der Server hält kein gemeinsames Token mehr"


def test_legacy_server_api_token_is_ignored_with_warning(tmp_path, caplog):
    path = tmp_path / "c.toml"
    path.write_text('[server]\napi_token = "alt"\nport = 9000\n', encoding="utf-8")
    cfg = load_config(path)
    assert cfg.server.port == 9000
    assert "api_token" in caplog.text


def test_load_config_rejects_unknown(tmp_path):
    path = tmp_path / "c.toml"
    path.write_text("[agent]\npoll_intervall = 1\n", encoding="utf-8")
    with pytest.raises(ValueError, match="poll_intervall"):
        load_config(path)


def test_explicit_missing_config(tmp_path):
    with pytest.raises(FileNotFoundError):
        load_config(tmp_path / "fehlt.toml")


def test_migrations_match_models(db):
    """Schlägt fehl, wenn models.py geändert wurde, ohne eine Migration anzulegen."""
    with db.engine.begin() as conn:
        try:
            command.check(alembic_config(conn))
        except AutogenerateDiffsDetected as exc:  # pragma: no cover
            pytest.fail(f"Migration fehlt: {exc}")


def test_copy_database(db, tmp_path):
    with db.session() as s:
        ingest.upsert_disk(s, "pc", make_disk())
    target = f"sqlite:///{(tmp_path / 'copy.db').as_posix()}"
    counts = copy_database(db.url, target)
    assert counts["disks"] == 1 and counts["volumes"] == 1
    with pytest.raises(RuntimeError, match="nicht leer"):
        copy_database(db.url, target)
    copied = Database(target)
    with copied.session() as s:
        from diskatlas.services.queries import load_disks

        assert load_disks(s)[0].display_name == "Archiv"
    copied.dispose()


def test_example_config_copies_identical():
    """config.example.toml liegt im Repo-Wurzelverzeichnis und im Paket (für `config --init`)."""
    from pathlib import Path

    root = Path(__file__).resolve().parent.parent
    packaged = root / "src" / "diskatlas" / "config.example.toml"
    assert (root / "config.example.toml").read_text() == packaged.read_text()
    import tomllib

    tomllib.loads(packaged.read_text())  # muss gültiges TOML sein
