"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 20:15:12.106677
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disk_key', sa.String(length=200), nullable=False),
    sa.Column('serial', sa.String(length=200), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('wwn', sa.String(length=200), nullable=True),
    sa.Column('transport', sa.String(length=50), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('rotational', sa.Boolean(), nullable=True),
    sa.Column('removable', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('custom_name', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('health', sa.String(length=20), nullable=False),
    sa.Column('smart_passed', sa.Boolean(), nullable=True),
    sa.Column('temperature_c', sa.Integer(), nullable=True),
    sa.Column('power_on_hours', sa.Integer(), nullable=True),
    sa.Column('power_cycles', sa.Integer(), nullable=True),
    sa.Column('reallocated_sectors', sa.Integer(), nullable=True),
    sa.Column('pending_sectors', sa.Integer(), nullable=True),
    sa.Column('uncorrectable_sectors', sa.Integer(), nullable=True),
    sa.Column('percentage_used', sa.Integer(), nullable=True),
    sa.Column('smart_checked_at', sa.DateTime(), nullable=True),
    sa.Column('smart_error', sa.Text(), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('last_host', sa.String(length=200), nullable=True),
    sa.Column('last_device', sa.String(length=200), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disk_key')
    )
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('disk_labels',
    sa.Column('disk_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disk_id'], ['disks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('disk_id', 'label_id')
    )
    op.create_table('smart_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disk_id', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('health', sa.String(length=20), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('temperature_c', sa.Integer(), nullable=True),
    sa.Column('power_on_hours', sa.Integer(), nullable=True),
    sa.Column('reallocated_sectors', sa.Integer(), nullable=True),
    sa.Column('pending_sectors', sa.Integer(), nullable=True),
    sa.Column('uncorrectable_sectors', sa.Integer(), nullable=True),
    sa.Column('percentage_used', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disk_id'], ['disks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('smart_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smart_snapshots_disk_id'), ['disk_id'], unique=False)

    op.create_table('volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disk_id', sa.Integer(), nullable=False),
    sa.Column('volume_key', sa.String(length=300), nullable=False),
    sa.Column('device', sa.String(length=200), nullable=True),
    sa.Column('fs_type', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('fs_uuid', sa.String(length=200), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('used_bytes', sa.BigInteger(), nullable=True),
    sa.Column('free_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mountpoint', sa.String(length=1000), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('active_scan_id', sa.String(length=36), nullable=True),
    sa.Column('index_status', sa.String(length=20), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('index_errors', sa.Integer(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('file_bytes', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['disk_id'], ['disks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disk_id', 'volume_key', name='uq_volume_disk_key')
    )
    with op.batch_alter_table('volumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volumes_disk_id'), ['disk_id'], unique=False)

    op.create_table('files',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('volume_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('extension', sa.String(length=50), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['volume_id'], ['volumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index('ix_files_extension', ['extension'], unique=False)
        batch_op.create_index('ix_files_name', ['name'], unique=False)
        batch_op.create_index('ix_files_volume_scan', ['volume_id', 'scan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index('ix_files_volume_scan')
        batch_op.drop_index('ix_files_name')
        batch_op.drop_index('ix_files_extension')

    op.drop_table('files')
    with op.batch_alter_table('volumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volumes_disk_id'))

    op.drop_table('volumes')
    with op.batch_alter_table('smart_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smart_snapshots_disk_id'))

    op.drop_table('smart_snapshots')
    op.drop_table('disk_labels')
    op.drop_table('labels')
    op.drop_table('disks')
    # ### end Alembic commands ###
