"""disk product line

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-23 23:02:43.916400
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_line', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disks', schema=None) as batch_op:
        batch_op.drop_column('product_line')

    # ### end Alembic commands ###
